// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBiFEtB0avT8nsJ2wrDOw3HKhQnZRJHCQ',
    appId: '1:168088285530:web:3edaac8cc9d10e36ecc363',
    messagingSenderId: '168088285530',
    projectId: 'docendo-chat',
    authDomain: 'docendo-chat.firebaseapp.com',
    storageBucket: 'docendo-chat.appspot.com',
    measurementId: 'G-MTTMCLW3JP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_4IfA1GkW_GxBxa_n_esTFdQ06q4wMVA',
    appId: '1:168088285530:android:93de7e4abe5405d2ecc363',
    messagingSenderId: '168088285530',
    projectId: 'docendo-chat',
    storageBucket: 'docendo-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf-SVbKZ1gcgIvrxOheKosleBfo9diT5U',
    appId: '1:168088285530:ios:b9e13cd510751b90ecc363',
    messagingSenderId: '168088285530',
    projectId: 'docendo-chat',
    storageBucket: 'docendo-chat.appspot.com',
    iosClientId: '168088285530-9vibh5iuidmsdghqu2qs77j4jj60pvsf.apps.googleusercontent.com',
    iosBundleId: 'com.example.docendoChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf-SVbKZ1gcgIvrxOheKosleBfo9diT5U',
    appId: '1:168088285530:ios:b9e13cd510751b90ecc363',
    messagingSenderId: '168088285530',
    projectId: 'docendo-chat',
    storageBucket: 'docendo-chat.appspot.com',
    iosClientId: '168088285530-9vibh5iuidmsdghqu2qs77j4jj60pvsf.apps.googleusercontent.com',
    iosBundleId: 'com.example.docendoChat',
  );
}
